### ISSUE TITLE
Client crash activating interdimensional pipe

### ISSUE THREAD

**Issue by CplPibald** [CD4017BE/VerticallyStackedDimensions#21]
CD4017BE_lib-1.12.2-6.4.8
VerticalDimensionStack-1.12.2-0.1.5
Forge 14.23.5.2836

Connected to dedicated server

Place chest (ActuallyAdditions crate) in very bottom of upper world
Go to lower world and place interdimensional pipe on portal block corresponding to chest.
Connect TE itemducts to pipe items upward.
(Possibly break chest, and then re-place it - player could not remember if they did this)

Shift-right-click on interdimensional pipe block

Expected: Removes ID pipe
Actual: Client crash

```
java.lang.NullPointerException: Unexpected error
	at cd4017be.lib.util.DimPos.getWorldServer(DimPos.java:124)
	at cd4017be.dimstack.core.PortalConfiguration.getAdjacentPos(PortalConfiguration.java:327)
	at cd4017be.dimstack.core.PortalConfiguration.getAdjacentPos(PortalConfiguration.java:309)
	at cd4017be.dimstack.tileentity.DimensionalPipe.onActivated(DimensionalPipe.java:148)
	at cd4017be.lib.block.AdvancedBlock.func_180639_a(AdvancedBlock.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
```

[Full crash report](https://paste.ubuntu.com/p/5TCtGQxByB/)

**Comment by CplPibald** [comment]
Don't know if this is the same issue, but I notice that breaking the chest in the upper world does not remove the pipe block in the lower world.  Normally breaking a block removes the transition portal block from the connected world, but it doesn't seem to work if the portal block has the pipe upgrade.

Breaking the block that a pipe is connected to should probably delete the pipe and transition block from the connected world.

**Comment by CplPibald** [comment]
Is there a release with this fix yet?
